### ISSUE TITLE
this is not working on my vscode it gives me a error which says this      ....Error fetching Bootstrap CSS from CDN: AxiosError: Request failed with status code 404

### ISSUE THREAD

**Issue by nooh-cloud** [hossaini310/bootstrap-intellisense#21]

**Comment by hossaini310** [comment]
Hello, can you please show your cdn link

**Comment by cboncales** [comment]
> Hello, can you please show your cdn link

does it work in downloaded bootstrap file?

<link rel="stylesheet" href="css/bootstrap.min.css" />

**Comment by cboncales** [comment]
it gives me this error too

Error fetching Bootstrap CSS from CDN: AxiosError: Request failed with status code 404

**Comment by hossaini310** [comment]
thanks for the issue, it should work now

**Comment by fiveStars-coder** [comment]
The issue is still there. Bootstrap file is downloaded locally, Bootstrap version is 5.3.2 - correctly identified in the VSCode. VS Code version is 1.94, the extension is auto-updated. Would really appreciate resolution :)
![image](https://github.com/user-attachments/assets/d2675d64-a992-4f6e-a9fb-44b44a2c8762)
![image](https://github.com/user-attachments/assets/9f8a9bb3-837a-4f46-b998-000833e0f3a1)

**Comment by hossaini310** [comment]
@fiveStars-coder see if it works for you now. v1.5.7

**Comment by fiveStars-coder** [comment]
Thank you, works now - no issues.
